### ISSUE TITLE
pntr_play_sound not defined on web

### ISSUE THREAD

**Issue by konsumer** [RobLoach/pntr_app#131]
![image](https://github.com/user-attachments/assets/5c787f4b-fc04-4e16-9c1f-7f102cd3c89d)

I am defining `PNTR_APP_WEB` and everyhting else works.

[Here]( https://konsumer.js.org/pntr_smb/) you  can see issue, and [here](https://github.com/konsumer/pntr_smb) is code.

**Comment by RobLoach** [comment]
I think this is fixed now?

**Comment by RobLoach** [comment]
Maybe we need to do a...
```
#define PNTR_APP_API EMSCRIPTEN_KEEPALIVE
```

... or something?

**Comment by konsumer** [comment]
Test app works fine now, with fresh clone, updated to master.) I still get the error, but it's playing sound.

Looking at error, I think issue is here:

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/75f7a2fb-52e1-4443-ab21-974c64b001b2" />

It should be calling `Module.pntr_play_sound(sound, loop);` or `pntr_app_web_play_sound` (since `pntr_play_sound` is not defined.) I can PR for a fix.
